# Generated by Django 4.0 on 2021-12-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfast', '0003_update_payfastorder_m_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfastorder',
            name='trusted',
            field=models.BooleanField(null=True),
        ),
    ]
